version: '3.0'

services:
  django:
    build: 
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_image
    ports:
      - 8000:8000
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - .:/app
    command: /start
    depends_on: 
      - db

  db:
    image: postgres
    container_name: postgres_cont
    env_file: ./.envs/.local/.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    
volumes:
  pgdata:
