# Generated by Django 4.0.10 on 2023-03-17 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_address_user'),
        ('product', '0004_product_color_product_size'),
        ('order', '0002_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.size'),
        ),
    ]
