# Generated by Django 4.0.10 on 2023-04-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_fee',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=4, default='120.00', max_digits=10),
        ),
    ]
