# Generated by Django 4.0.10 on 2023-03-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_color_product_size'),
        ('order', '0003_order_address_alter_orderitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitems',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.size'),
            preserve_default=False,
        ),
    ]
