# Generated by Django 4.0.10 on 2023-03-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
