# Generated by Django 4.0.10 on 2023-03-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_mobile_number_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
