# Generated by Django 4.0.10 on 2023-03-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_otp',
            field=models.CharField(max_length=6),
        ),
    ]
