# Generated by Django 4.0.10 on 2023-03-16 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_color_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='description',
        ),
    ]
